
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziqelnvwphgwbngsbkit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppcWVsbnZ3cGhnd2JuZ3Nia2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjY3MzIsImV4cCI6MjA1ODQwMjczMn0.jK-s-H-Ee1RaeSAJw0PBvSBqn2we4gUgE7YOzegp7W0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});

// Type-safe table names for use in queries
export const TABLES = {
  PROFILES: 'profiles',
  AIRDROPS: 'airdrops',
  TESTNETS: 'testnets',
  TOOLS: 'tools',
  VIDEOS: 'videos',
  RANKINGS: 'rankings',
  AIRDROP_CATEGORIES: 'airdrop_categories',
  TESTNET_CATEGORIES: 'testnet_categories',
  TOOL_CATEGORIES: 'tool_categories',
  VIDEO_CATEGORIES: 'video_categories',
} as const;
